### ISSUE TITLE
Does this extended flashsim depend on disksim？

### ISSUE THREAD

**Issue by cyb3727** [MatiasBjorling/flashsim#15]
I know the origin flashsim is developed obove disksim, and I don't know what's the relations between the origin flashsim code and your new extended flashsim project code. Thank you!

**Comment by MatiasBjorling** [comment]
Hi, it is not based on Disksim. It can be used standalone. It implements DFTL, BAST, and FAST FTL to be used for simulation.

**Comment by cyb3727** [comment]
Great!

**Comment by alinezhad2018** [comment]
I there any instruction for compile and run flashsim independent of disksim?

**Comment by MatiasBjorling** [comment]
You will need to run make to compile it. It is not dependent on disksim.

**Comment by ziatabar** [comment]
is it possible to add this code to disksim? how ?

**Comment by ziatabar** [comment]
after running makefile, it create several executable file such as "raid, biomodal, cfliptrace, ..." . 
I wonder which one we should run for further testing and how can I force my own trace to them?
