### ISSUE TITLE
 FlashSim error

### ISSUE THREAD

**Issue by shailesh23jan** [MatiasBjorling/flashsim#16]
Dear Matias,

  I am working on  simulator FlashSim. I got the  following error while try to run simulator.
"
test: ssd_bm.cpp:94: void ssd::Block_manager::get_page_block(ssd::Address&, ssd::Event&): Assertion `free_list.size() != 0' failed.
RUN FINISHED; Aborted; core dumped; real time: 480ms; user: 10ms; system: 130ms  "

Please help me out to remove the above error so that I can simulate my research work on FlashSim. Kindly suggest me  about how to give the trace file as input to FlashSim.

I will be very thankful for your suggestions.

Thanks & Regards

Shailesh Kumar

Research Fellow
MMM University of Technology, Gorakhpur

India

**Comment by phyloflash** [comment]
I got the same problem.

What I tried to do is to use different g++ version to -std=c++1y but it still remains the same.

**Comment by eunjeung** [comment]
Hello
I had the same problem.
I keep having this problem like this.

test: ssd_bm.cpp:94: void ssd::Block_manager::get_page_block(ssd::Address&, ssd::Event&): Assertion `free_list.size() != 0' failed.

**Comment by MatiasBjorling** [comment]
Thanks
