### ISSUE TITLE
Input Trace Format

### ISSUE THREAD

**Issue by arh** [MatiasBjorling/flashsim#2]
Hi Matias, 

Would you please let us know the input trace file format or update a sample trace file with a few lines ?

Thanks
Alireza

**Comment by alinezhad2018** [comment]
hi,
I have problem in running  flashsim...after compile and make it....
after running makefile, it create several executable file such as "raid, biomodal, cfliptrace, ..." .
I wonder which one we should run for further testing and how can I force my own trace to them?

thank you
